const router = require('express').Router()
const adminController = require('../CONTROLLERS/adminController/loginController')
const categoryController = require('../CONTROLLERS/adminController/categoryController')
const productController = require('../CONTROLLERS/adminController/productController')
const userController = require('../CONTROLLERS/adminController/userController')
const bannerController = require('../CONTROLLERS/adminController/bannerController')
const couponController = require('../CONTROLLERS/adminController/couponController')
const orderController = require('../CONTROLLERS/adminController/orderController')
const uploadToFile = require('../MIDDLEWARE/multer')
const { orderManagementGet } = require('../CONTROLLERS/adminController/orderController')
const auth = require('../MIDDLEWARE/authentication').verifyLogin


 
router.get('/',adminController.loginGet)
router.post('/',adminController.loginPost)
router.use(auth)
router.get('/home',adminController.homeGet)
router.get('/categories',categoryController.categoriesGet)
router.post('/categories',uploadToFile.single('picture',12),categoryController.categoriesPost)
router.get('/categoryAction',categoryController.categoryAction)
router.get('/products',productController.productGet) 
router.get('/addProduct',productController.addProductGet)
router.post('/addProduct',uploadToFile.array('picture',12),productController.addProductPost)
router.get('/productAction',productController.productAction)
router.get('/editProduct/:id',productController.productEditGet)
router.post('/editProduct/:id',uploadToFile.array('picture',12),productController.productEditPost)
router.get('/banner',bannerController.bannerGet)
router.get('/addBanner',bannerController.addBannerGet)
router.post('/addBanner',uploadToFile.single('picture',12),bannerController.addBannerPost)
router.get('/userDetails',userController.userGet)
router.get('/userAction',userController.userAction)
router.get('/coupons',couponController.couponGet)
router.post('/coupons',couponController.couponPost)
router.get('/couponAction',couponController.couponAction)
router.get('/orderManagement',orderController.orderManagementGet)
router.get("/orderedProductDetails/:id",orderController.singleOrderDetails)
router.post('/changeOrderStatus',orderController.changeOrderStatus)
router.get('/logout',adminController.logout)

module.exports = router
