const router = require('express').Router()
const loginControllers = require('../CONTROLLERS/userController/login')
const cartControllers = require('../CONTROLLERS/userController/cart')
const categoryControllers = require('../CONTROLLERS/userController/catergory')
const checkoutControllers = require('../CONTROLLERS/userController/checkout')
const wishlistControllers = require('../CONTROLLERS/userController/wishlist')
const couponController = require('../CONTROLLERS/userController/coupon')
const orderController = require('../CONTROLLERS/userController/order')
const auth = require('../MIDDLEWARE/authenticationUser').verifyLoginUser


const userController =require('../CONTROLLERS/userController/controller')

router.get('/',loginControllers.homePage)
router.get('/login',loginControllers.loginPage)
router.post('/login',loginControllers.postLoginPage)
router.get('/signup',loginControllers.getSignupPage)
router.post('/signup',loginControllers.postSignupPage)
router.get('/otpVerify',loginControllers.otpGet)
router.post('/otpVerify',loginControllers.otpPost)
router.get('/shop',categoryControllers.categoryPage)
router.get('/categoryShop/:id',categoryControllers.singleCategoryPage)
router.get('/product/:id',userController.getProduct)
router.get('/logout',auth,loginControllers.logout)   
router.get('/wishlist',auth,wishlistControllers.getWishlist)
router.post('/addWishlist',auth,wishlistControllers.addWishlist) 
router.get('/cart',auth,cartControllers.cartPage)
router.post('/addToCart/:id',auth,cartControllers.addToCart)
router.post('/changeProductQuantity',auth,cartControllers.changeQuantity)
router.post('/removeProductCart',auth,cartControllers.removeFromCart)
router.post('/couponSubmit',auth,couponController.applyCoupon)
router.get('/checkout',auth,checkoutControllers.checkoutPage)
router.post('/checkout',auth,checkoutControllers.checkoutPagePost)
router.post('/placeOrder',auth,checkoutControllers.placeOrder)
router.post('/addAddress',auth,checkoutControllers.addressAdd)
router.get('/confirmation',auth,checkoutControllers.orderConfirmation)
router.post('/verifyPayment',auth,checkoutControllers.onlinePaymentVerify)
router.get('/orderDetails',auth,orderController.getOrderDetails)
router.get('/singleOrderDetails/:id',auth,orderController.getSingleOrderDetails)
router.get('/contact',auth,userController.getContact)
router.get('/userProfile',auth,userController.getUserProfile)
router.get('/changePass',auth,userController.getChangePass)


module.exports = router; 